import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import NavbarDemo from "@/components/Navbar";
import { NFTProvider } from "@/context/NFTContext"; // Import NFTProvider

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen flex flex-col`}
        suppressHydrationWarning // Add this to ignore hydration mismatches on body
      >
        <NFTProvider>
          {" "}
          {/* Wrap the content with NFTProvider */}
          <NavbarDemo />
          <main className="pt-20 mt-28">{children}</main>
          <Footer />
        </NFTProvider>
      </body>
    </html>
  );
}
